### ISSUE TITLE
folly-2024.03.18 is not available

### ISSUE THREAD

**Issue by jeongseok-meta** [conda-forge/folly-feedstock#175]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I noticed that folly-2024.03.18 was checked in by https://github.com/conda-forge/folly-feedstock/pull/173, but the packages are not visible on the [pixi package website](https://prefix.dev/channels/conda-forge/packages/folly) and cannot be downloaded using [pixi](https://prefix.dev/) (I am using the conda packages through this package manager). Is it simply taking a long time or is it stuck at some stage? Is there a way to check its status? I apologize if this is not the appropriate place to ask about this.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by jjerphan** [comment]
Indeed, looking at [this PR's merge commit](https://github.com/conda-forge/folly-feedstock/commit/0480390475e4fa1296dcaacd1bbc3ad6b6bf8119), it seems the CI has not run.

**Comment by jeongseok-meta** [comment]
Ah, that explains it. Could we manually trigger the CI?

**Comment by jjerphan** [comment]
I guess it is possible,  but I can't do it myself.

**Comment by jjerphan** [comment]
Actually:
 - the CI checks ran
 - I can rerun checks (the option is just slightly hidden in the "Action" panel), and I reran them
 
Yet both runs failed because "[I] cannot automerge" even-though I am a maintainer; see:
- [the first workflow run logs](https://github.com/conda-forge/folly-feedstock/actions/runs/8378747372/job/22944041604#step:4:11)
- [the second workflow run logs](https://github.com/conda-forge/folly-feedstock/actions/runs/8378747372/job/22974776873#step:4:11)

**Comment by jjerphan** [comment]
The only solution is to push an empty commit, like @wolfv (thanks): https://github.com/conda-forge/folly-feedstock/commit/276111222c243a88ae85d412e0ea5e30d138ca45
